### ISSUE TITLE
Installation through HACS doesn't work

### ISSUE THREAD

**Issue by henrikwils** [r-renato/hass-xiaomi-mi-flora-and-flower-care#10]
I installed this through HACS and added the bit to configuration.yaml as described, but Home Assistant says it doesn't know the platform.

**Comment by r-renato** [comment]
Please, post here your configuration.

**Comment by henrikwils** [comment]
huahuacaocao:
  username: h...@w....info
  password: ***
  region: EU

Config validator says:
Configuration invalid
Component error: huahuacaocao - Integration 'huahuacaocao' not found.

**Comment by r-renato** [comment]
do you have restarted ha? if yes, try to put component in debug mode and post here the log.
You have to collect the only rows that contain `[custom_components.huahuacaocao]`.

To put the component in debug mode you must add the following and restart HA:
`custom_components.huahuacaocao: debug`

Example:

```
# Logging
logger:
  logs:
    custom_components.huahuacaocao: debug
```

**Comment by henrikwils** [comment]
Yes it was restarted. Nothing in the log - It was just as if it wasn't installed what so ever. But maybe my HACS was wonky. It was out of date, and crashed when I tried to update it.

Now I no longer see your component in there - Did you pull it?

Instead I installed manually - I can see the entities, but I'm not sure how to import the lovelace card? Your documentation points to a file that seems to be installed through HACS, and is not in the git as far as I can see?

**Comment by r-renato** [comment]
The custom component also provides for the installation of the lovelace card. You can found the javascript card in the folder `homeassistant/www/community/hacs-card-for-xiaomi-mi-flora-and-flower-care`. Follow the instructions in the readme to use it.
