### ISSUE TITLE
Values "unknown" not highlighted in red colour

### ISSUE THREAD

**Issue by WojtekK78** [r-renato/hass-xiaomi-mi-flora-and-flower-care#11]
When no data is coming from MQTT/Mosquito integration via https://github.com/zewelor/bt-mqtt-gateway integration it's diplayed in white fonts as "unknown". 

For clarity & consistency could "unknown" be also be formatted in Red fonts colour. The same as it's now for native integration when there is "unavaliable" value diplayed in Red fonts colour ?

![image](https://user-images.githubusercontent.com/20930258/81798213-10acd900-9510-11ea-802b-d35441412509.png)

**Comment by r-renato** [comment]
Ok, i can to do this.

**Comment by r-renato** [comment]
Component updated. Please check if it works as required.

Thanks, bye,
Renato

**Comment by WojtekK78** [comment]
Red n/a working ok now. One more thing I'see that for MQTT messages part of icons (lux, temperature and battery) are missing from card -  per screenshot on right side. Othere icons are there, can we tackle this also under this issue :) 
Again original mi-flora HA integration shows all icons

![image](https://user-images.githubusercontent.com/20930258/81812035-d77f6380-9525-11ea-828e-c514d3640c2d.png)

**Comment by r-renato** [comment]
Do you want try again? I have released a new version with inside the bugfix.

**Comment by WojtekK78** [comment]
All, good from my perspective. Both HA (left side) and MQTT based (right side) mi-flora cards looks OK. Thanks for quick fix !

![image](https://user-images.githubusercontent.com/20930258/81840224-f511f480-9548-11ea-80f4-90fb55f8b403.png)
