### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by cbagger** [r-renato/hass-xiaomi-mi-flora-and-flower-care#6]
Hi,

Problems with installing this at HACS, however i installed in manuel.

When i have the card in, and works fine, i can't figure out how to hide Maintenance? It's like in the card? Are there somehow i can hide it? 

![2020-03-12_17h11_36](https://user-images.githubusercontent.com/51855681/76541892-89e26e00-6484-11ea-96b0-d631a16ca764.png)

**Comment by r-renato** [comment]
At moment no, but I can work to do this.

**Comment by cbagger** [comment]
So your card is showing it like this too?
I doesn't look like this with the maintenance guide allways showed in the repo?

**Comment by r-renato** [comment]
Hi,
I have updated the custom componet. Now you can customize the card and hide/show the sessions of info and maintenance. For example, a possible configuration is the following:

```
type: custom:xiaomi-mi-flora-and-flower-care-card
name: "Zamioculcas Zamiifolia"
zone_name: "Kitchen"
display:
    - info
    - maintenance
```

**Comment by cbagger** [comment]
Hi again,

Nice - but i cant make it work.
I dont know if you have the same issues as me? 
The maintenance is like showed in the card allways as you see in the first picture.
It's not only when i press the Maintenance icon.

I tried update rep with the new, and didnt make any difference here?
Might be doing something wrong, i dont know?

**Comment by r-renato** [comment]
Hi, clear your browser cache and retry.
If you use the "Lovelace Gen" component you can replace:

```
resources:
  - url: /community_plugin/hacs-card-for-xiaomi-mi-flora-and-flower-care/hacs-card-for-xiaomi-mi-flora-and-flower-care.js
    type: js
```
with

```
resources:
  - url: !file /community_plugin/hacs-card-for-xiaomi-mi-flora-and-flower-care/hacs-card-for-xiaomi-mi-flora-and-flower-care.js
    type: js
```

**Comment by cbagger** [comment]
Thank you so much - it works wonderful now! :)

**Comment by r-renato** [comment]
Well, have fun. :D
