### ISSUE TITLE
Unable to use the component if the directory "www/community" doesn't exist

### ISSUE THREAD

**Issue by limeryls** [r-renato/hass-xiaomi-mi-flora-and-flower-care#7]
I just installed the component but I can't use it because there is an error after restarting hassio.
Indeed, the directory /config/www/community doesn't exist in my installation.

I have to create it manually in order to avoid the error on restart hassio and to be able to use this component.

https://github.com/r-renato/hass-xiaomi-mi-flora-and-flower-care/blob/85fbc7dc2bd4723b9a96e78271f4db49005d914e/custom_components/huahuacaocao/__init__.py#L82

**Comment by r-renato** [comment]
Hi, thank you for the notification. I'm working on fixing it as soon as possible.
Renato

**Comment by r-renato** [comment]
Fixed.

Thanks for the notification.
Bye,
Renato
