### ISSUE TITLE
HACS installation

### ISSUE THREAD

**Issue by Alloc186** [r-renato/hass-xiaomi-mi-flora-and-flower-care#9]
Hi I cant make it work. if I want to install it from HACS page it gives me this error.

Take a look, its in screenshoot.

![2020-03-27](https://user-images.githubusercontent.com/37019014/77752331-a3102080-7027-11ea-8b87-e91796537a4b.png)

**Comment by r-renato** [comment]
Hi, 
this appears to be an installation problem. 

Sorry but I can not help you. You must open the issue directly to HACS https://github.com/hacs/frontend

Thanks, bye.
Renato

**Comment by d3nnis0** [comment]
@r-renato Same error for me, other HACS solutions work without an issue. From my point of view it probably is related to your solution.

**Comment by r-renato** [comment]
HACS performs a set of checks before add a custom component to her repository and it only does so if all checks are ok. Passed all checks the custom component is made available to the ha users. HACS is responsible for the installation, the component developer is not.
